run R CMD check using rcmdcheck

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -123,6 +123,10 @@ jobs:
           R CMD config CXXPICFLAGS
           g++ --version
 
+      - name: Check
+        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
+        shell: Rscript {0}
+
       - name: Build, Install, Check
         id: build-install-check
         uses: grimbough/bioc-actions/build-install-check@v1
@@ -138,20 +142,20 @@ jobs:
         run: |
           cat /home/runner/work/Rhisat2/Rhisat2.Rcheck/00install.out
 
-      - name: Print install.out file (windows hard-coded name)
-        if: runner.os == 'Windows' && failure()
-        run: find . -name 'Rhisat2.install-out.txt' -exec cat '{}' \; || true
-        shell: bash
-
-      - name: Print install.out file (any location)
-        if: failure()
-        run: find . -name '00install.out' -exec cat '{}' \; || true
-        shell: bash
-
-      - name: Print check.out file (any location)
-        if: failure()
-        run: find . -name '00check.log' -exec cat '{}' \; || true
-        shell: bash
+#      - name: Print install.out file (windows hard-coded name)
+#        if: runner.os == 'Windows' && failure()
+#        run: find . -name 'Rhisat2.install-out.txt' -exec cat '{}' \; || true
+#        shell: bash
+#
+#      - name: Print install.out file (any location)
+#        if: failure()
+#        run: find . -name '00install.out' -exec cat '{}' \; || true
+#        shell: bash
+#
+#      - name: Print check.out file (any location)
+#        if: failure()
+#        run: find . -name '00check.log' -exec cat '{}' \; || true
+#        shell: bash
 
       - name: Show testthat output
         if: always()
@@ -163,7 +167,9 @@ jobs:
         uses: actions/upload-artifact@master
         with:
           name: ${{ runner.os }}-bioc${{ matrix.config.bioc }}-results
-          path: ${{ steps.build-install-check.outputs.check-dir }}
+          path: |
+            check
+            ${{ steps.build-install-check.outputs.check-dir }}
 
       - name: Test coverage
         if: matrix.config.os == 'macOS-latest'
